### PR TITLE
Replace `caltype` with `use_leap_years`

### LINKED ISSUE #28: Remove `caltype` option for ESM1.6
### Background

CICE in ESM1.6 determines the calendar type (proleptic gregorian, noleap, constant month-length) from the  `caltype` option in the [`input_ice/coupling` namelist](https://github.com/ACCESS-NRI/cice5/blob/28986316a06d4ae86086cda26ec3d381d22f9018/drivers/access/cpl_parameters.F90#L84-L87). It's used in the [custom access calendar routines](https://github.com/ACCESS-NRI/cice5/blob/28986316a06d4ae86086cda26ec3d381d22f9018/source/ice_calendar.F90#L556-L626) which calculate the current date based on the internal model time. Additionally, the ESM1.6+cice5 prototype in `payu` uses `caltype` to [calculate the run length](https://github.com/payu-org/payu/blob/120480a9ce2dd7bd4538ad26ff8841ec73efe6e9/payu/models/access_esm1p6.py#L159-L165) of each simulation. `caltype` is not originally part of CICE and only appears in the access coupled model branches.

This works well for setting the model internal date, however CICE5 also has it's own `use_leap_years` flag for setting the calendar type. While the two parameters have same purpose, they affect different parts of the CICE code. Problems occur when they aren't consistent.

For example:  while `caltype` determines the internal model calendar, `use_leap_years` determines the calendar attribute in the netCDF output. If you have `caltype=0` (noleap), and `use_leap_years=.true.`, you get output with wrong dates:

```
$ ncdump -t -v time  iceh.0104-01-01.nc
...
float time(time) ;
		time:long_name = "model time" ;
		time:units = "days since 0001-01-01 00:00:00" ;
		time:calendar = "Gregorian" ;
		time:bounds = "time_bounds" ;
...
time = "0103-12-08" ;
```

The reverse settings luckily cause the model to crash once it tries to write the first output.

### Proposed change:

From what I can understand,  `caltype` and `use_leap_years` are both meant to do the same thing. I think it would be more intuitive to use just one – probably `use_leap_years` as it comes from upstream. This would involve swapping a few conditionals involving `caltype`, and making parallel changes in the esm1.6 payu driver.

### Complications:
For values `caltype > 1`, it takes on another meaning: It sets the model to use constant-length months of lenght `caltype` days (see [here](https://github.com/ACCESS-NRI/cice5/blob/0a84ab156217cc8e782affbe7f13071e59a230d8/source/ice_calendar.F90#L628-L638)). This might be useful for running a 360 day calendar, which is also supported by the UM.

However, this option also doesn't work with the history writing routines. It would be better to instead use the existing `days_per_year=360` capability, rather than setting `caltype=30`.

We would lose the ability to run with very custom calendars like 10-day months, but I don't think this is supported on the UM side anyway.
 

Pinging @anton-seaice

### PR DESCRIPTION
**Pull request by blimlim**
Closes #28 and forms part of work in simplifying the calendar in the coupled model (if time permits).

The CM2 setup had two separate parameters for specifying the calendar type: `use_leap_years` from core CICE, and `caltype` added for the ACCESS models. It was possible for these to not match, meaning different calendars could be used in different parts of the code.

This PR removes `caltype`, replacing all instances with `use_leap_years`. If merged, `caltype` should be removed from the configuration namelists.  This change will require the [changes shown here](https://github.com/ACCESS-NRI/payu/commit/399d945faf68fe04837e9da3487dc3b12dbddecc) to the ESM1.6 payu driver.

Removing `caltype` does remove the ability to specify arbitrary month lengths, however this feature wouldn't have been supported in the coupled model, and also doesn't look like it was properly supported within CICE.

### CODE REVIEW

File: source/ice_calendar.F90 [hunk 1]
```diff
@@ -152,7 +152,7 @@ subroutine init_calendar
       end if
       
 #ifdef AusCOM
-      if ((days_year(year_init) == 366) .and. (caltype == 1)) days_per_year = 366
+      if (days_year(year_init) == 366) days_per_year = 366
```
Comment (blimlim) [inline source/ice_calendar.F90:155]: Removed the `caltype`/`use_leap_years` check here since this check is already performed in the  `days_year` function.

File: source/ice_calendar.F90 [hunk 2]
```diff
@@ -575,111 +575,77 @@ subroutine get_idate(ttime, khfin, kdfin, kmfin, kyfin)
...
-  lleap = .FALSE.
-  days_year = 365.
-  IF (caltype .eq. 1) THEN
-    IF (MOD(year,  4) .eq. 0) lleap = .TRUE.
-    IF (MOD(year,100) .eq. 0) lleap = .FALSE.
-    IF (MOD(year,400) .eq. 0) lleap = .TRUE.
-  ENDIF
-  if (lleap) days_year = 366.
-ELSE
-  days_year = dayyr
```
Comment (blimlim) [inline source/ice_calendar.F90:681]: I guess removing this last line breaks support for a 360 day calendar. This would already be broken due to the call to `set_calendar` in line 239 which assumes a Gregorian calendar.

Is making the 360 day calendar functional something that's worth trying to work out?

**Comment by blimlim** [comment]
Notes on testing:

I've run the new code for three months on a leap year and non-leap year, with both `use_leap_years=.true.` and `use_leap_years=.false.`. I've also run the old code on a leap year and non-leap year with `caltype=1` and `caltype=0`.

### New code, `use_leap_years=.true.`, leap year:
Produces the following output:

<details>

```
iceh.0792-01-01.nc  iceh.0792-01-15.nc  iceh.0792-01-29.nc  iceh.0792-02-11.nc  iceh.0792-02-25.nc  iceh.0792-03-09.nc  iceh.0792-03-23.nc
iceh.0792-01-02.nc  iceh.0792-01-16.nc  iceh.0792-01-30.nc  iceh.0792-02-12.nc  iceh.0792-02-26.nc  iceh.0792-03-10.nc  iceh.0792-03-24.nc
iceh.0792-01-03.nc  iceh.0792-01-17.nc  iceh.0792-01-31.nc  iceh.0792-02-13.nc  iceh.0792-02-27.nc  iceh.0792-03-11.nc  iceh.0792-03-25.nc
iceh.0792-01-04.nc  iceh.0792-01-18.nc  iceh.0792-01.nc     iceh.0792-02-14.nc  iceh.0792-02-28.nc  iceh.0792-03-12.nc  iceh.0792-03-26.nc
iceh.0792-01-05.nc  iceh.0792-01-19.nc  iceh.0792-02-01.nc  iceh.0792-02-15.nc  iceh.0792-02-29.nc  iceh.0792-03-13.nc  iceh.0792-03-27.nc
iceh.0792-01-06.nc  iceh.0792-01-20.nc  iceh.0792-02-02.nc  iceh.0792-02-16.nc  iceh.0792-02.nc     iceh.0792-03-14.nc  iceh.0792-03-28.nc
iceh.0792-01-07.nc  iceh.0792-01-21.nc  iceh.0792-02-03.nc  iceh.0792-02-17.nc  iceh.0792-03-01.nc  iceh.0792-03-15.nc  iceh.0792-03-29.nc
iceh.0792-01-08.nc  iceh.0792-01-22.nc  iceh.0792-02-04.nc  iceh.0792-02-18.nc  iceh.0792-03-02.nc  iceh.0792-03-16.nc  iceh.0792-03-30.nc
iceh.0792-01-09.nc  iceh.0792-01-23.nc  iceh.0792-02-05.nc  iceh.0792-02-19.nc  iceh.0792-03-03.nc  iceh.0792-03-17.nc  iceh.0792-03-31.nc
iceh.0792-01-10.nc  iceh.0792-01-24.nc  iceh.0792-02-06.nc  iceh.0792-02-20.nc  iceh.0792-03-04.nc  iceh.0792-03-18.nc  iceh.0792-03.nc
iceh.0792-01-11.nc  iceh.0792-01-25.nc  iceh.0792-02-07.nc  iceh.0792-02-21.nc  iceh.0792-03-05.nc  iceh.0792-03-19.nc
iceh.0792-01-12.nc  iceh.0792-01-26.nc  iceh.0792-02-08.nc  iceh.0792-02-22.nc  iceh.0792-03-06.nc  iceh.0792-03-20.nc
iceh.0792-01-13.nc  iceh.0792-01-27.nc  iceh.0792-02-09.nc  iceh.0792-02-23.nc  iceh.0792-03-07.nc  iceh.0792-03-21.nc
iceh.0792-01-14.nc  iceh.0792-01-28.nc  iceh.0792-02-10.nc  iceh.0792-02-24.nc  iceh.0792-03-08.nc  iceh.0792-03-22.nc
```
</details>

Output dates seem ok:
```
ncdump -t -v time iceh.0792-02-29.nc
...
 time = "0792-02-29 12" ;

```

### New code, `use_leap_years=.true.`, non-leap year:

Produces the following output. The switching between leap and non-leap years looks ok:

<details>
```
iceh.0787-01-01.nc  iceh.0787-01-15.nc  iceh.0787-01-29.nc  iceh.0787-02-11.nc  iceh.0787-02-25.nc  iceh.0787-03-10.nc  iceh.0787-03-24.nc
iceh.0787-01-02.nc  iceh.0787-01-16.nc  iceh.0787-01-30.nc  iceh.0787-02-12.nc  iceh.0787-02-26.nc  iceh.0787-03-11.nc  iceh.0787-03-25.nc
iceh.0787-01-03.nc  iceh.0787-01-17.nc  iceh.0787-01-31.nc  iceh.0787-02-13.nc  iceh.0787-02-27.nc  iceh.0787-03-12.nc  iceh.0787-03-26.nc
iceh.0787-01-04.nc  iceh.0787-01-18.nc  iceh.0787-01.nc     iceh.0787-02-14.nc  iceh.0787-02-28.nc  iceh.0787-03-13.nc  iceh.0787-03-27.nc
iceh.0787-01-05.nc  iceh.0787-01-19.nc  iceh.0787-02-01.nc  iceh.0787-02-15.nc  iceh.0787-02.nc     iceh.0787-03-14.nc  iceh.0787-03-28.nc
iceh.0787-01-06.nc  iceh.0787-01-20.nc  iceh.0787-02-02.nc  iceh.0787-02-16.nc  iceh.0787-03-01.nc  iceh.0787-03-15.nc  iceh.0787-03-29.nc
iceh.0787-01-07.nc  iceh.0787-01-21.nc  iceh.0787-02-03.nc  iceh.0787-02-17.nc  iceh.0787-03-02.nc  iceh.0787-03-16.nc  iceh.0787-03-30.nc
iceh.0787-01-08.nc  iceh.0787-01-22.nc  iceh.0787-02-04.nc  iceh.0787-02-18.nc  iceh.0787-03-03.nc  iceh.0787-03-17.nc  iceh.0787-03-31.nc
iceh.0787-01-09.nc  iceh.0787-01-23.nc  iceh.0787-02-05.nc  iceh.0787-02-19.nc  iceh.0787-03-04.nc  iceh.0787-03-18.nc  iceh.0787-03.nc
iceh.0787-01-10.nc  iceh.0787-01-24.nc  iceh.0787-02-06.nc  iceh.0787-02-20.nc  iceh.0787-03-05.nc  iceh.0787-03-19.nc
iceh.0787-01-11.nc  iceh.0787-01-25.nc  iceh.0787-02-07.nc  iceh.0787-02-21.nc  iceh.0787-03-06.nc  iceh.0787-03-20.nc
iceh.0787-01-12.nc  iceh.0787-01-26.nc  iceh.0787-02-08.nc  iceh.0787-02-22.nc  iceh.0787-03-07.nc  iceh.0787-03-21.nc
iceh.0787-01-13.nc  iceh.0787-01-27.nc  iceh.0787-02-09.nc  iceh.0787-02-23.nc  iceh.0787-03-08.nc  iceh.0787-03-22.nc
iceh.0787-01-14.nc  iceh.0787-01-28.nc  iceh.0787-02-10.nc  iceh.0787-02-24.nc  iceh.0787-03-09.nc  iceh.0787-03-23.nc
```
</details>

### New code, `use_leap_years=.false.`, leap year:
Crashes in coupling as CICE stops earlier than the UM which is using the gregorian calendar. Work directory contains the following output:
<details>

```
iceh.0792-01-01.nc  iceh.0792-01-15.nc  iceh.0792-01-29.nc  iceh.0792-02-11.nc  iceh.0792-02-25.nc  iceh.0792-03-10.nc  iceh.0792-03-24.nc
iceh.0792-01-02.nc  iceh.0792-01-16.nc  iceh.0792-01-30.nc  iceh.0792-02-12.nc  iceh.0792-02-26.nc  iceh.0792-03-11.nc  iceh.0792-03-25.nc
iceh.0792-01-03.nc  iceh.0792-01-17.nc  iceh.0792-01-31.nc  iceh.0792-02-13.nc  iceh.0792-02-27.nc  iceh.0792-03-12.nc  iceh.0792-03-26.nc
iceh.0792-01-04.nc  iceh.0792-01-18.nc  iceh.0792-01.nc     iceh.0792-02-14.nc  iceh.0792-02-28.nc  iceh.0792-03-13.nc  iceh.0792-03-27.nc
iceh.0792-01-05.nc  iceh.0792-01-19.nc  iceh.0792-02-01.nc  iceh.0792-02-15.nc  iceh.0792-02.nc     iceh.0792-03-14.nc  iceh.0792-03-28.nc
iceh.0792-01-06.nc  iceh.0792-01-20.nc  iceh.0792-02-02.nc  iceh.0792-02-16.nc  iceh.0792-03-01.nc  iceh.0792-03-15.nc  iceh.0792-03-29.nc
iceh.0792-01-07.nc  iceh.0792-01-21.nc  iceh.0792-02-03.nc  iceh.0792-02-17.nc  iceh.0792-03-02.nc  iceh.0792-03-16.nc  iceh.0792-03-30.nc
iceh.0792-01-08.nc  iceh.0792-01-22.nc  iceh.0792-02-04.nc  iceh.0792-02-18.nc  iceh.0792-03-03.nc  iceh.0792-03-17.nc  iceh.0792-03-31.nc
iceh.0792-01-09.nc  iceh.0792-01-23.nc  iceh.0792-02-05.nc  iceh.0792-02-19.nc  iceh.0792-03-04.nc  iceh.0792-03-18.nc  iceh.0792-03.nc
iceh.0792-01-10.nc  iceh.0792-01-24.nc  iceh.0792-02-06.nc  iceh.0792-02-20.nc  iceh.0792-03-05.nc  iceh.0792-03-19.nc
iceh.0792-01-11.nc  iceh.0792-01-25.nc  iceh.0792-02-07.nc  iceh.0792-02-21.nc  iceh.0792-03-06.nc  iceh.0792-03-20.nc
iceh.0792-01-12.nc  iceh.0792-01-26.nc  iceh.0792-02-08.nc  iceh.0792-02-22.nc  iceh.0792-03-07.nc  iceh.0792-03-21.nc
iceh.0792-01-13.nc  iceh.0792-01-27.nc  iceh.0792-02-09.nc  iceh.0792-02-23.nc  iceh.0792-03-08.nc  iceh.0792-03-22.nc
iceh.0792-01-14.nc  iceh.0792-01-28.nc  iceh.0792-02-10.nc  iceh.0792-02-24.nc  iceh.0792-03-09.nc  iceh.0792-03-23.nc
```
</details>

### Old code, `caltype=1`, leap year:
Produces identical files as new code with`use_leap_years=.true.` in the leap year. Identical both in dates and data.

### Old code, `caltype=1`, non-leap year:
Produces identical files as new code with`use_leap_years=.true.` in the non-leap year. Identical both in dates and data.

### Old code, `caltype=0`, leap year:
Crashes due to the [`set_calendar` call](https://github.com/ACCESS-NRI/cice5/blob/8f074fa3afe165ee479572d4032b02d16a7879b3/source/ice_calendar.F90#L293) resetting `days_per_year` to 366.

**Comment by anton-seaice** [comment]
kind of a moot point, but probably don't make the whitespace changes so its easy in the future to know who changes what ?

**Comment by blimlim** [comment]
Good point. I'll revert the whitespace changes – should make the diff easier to read too

File: drivers/access/cpl_parameters.F90 [hunk 3]
```diff
@@ -82,7 +79,6 @@ module cpl_parameters
 real(kind=dbl_kind) :: iceberg_factor = 1.0
 !             
 namelist/coupling/       &
-         caltype,        &
```
Comment (anton-seaice) [inline drivers/access/cpl_parameters.F90:85]: What I was thinking was make the default value for caltype to -99, and leave it in this section. If it's set to any value other than -99, then abort with the message "Caltype not used, remove from namelist"

File: source/ice_calendar.F90 [hunk 4]
```diff
@@ -588,7 +588,7 @@ subroutine get_idate(ttime, khfin, kdfin, kmfin, kyfin)
       !* Leap years
       !
       lleap = .FALSE.
-      IF (caltype .eq. 1) THEN
+      IF (use_leap_years) THEN
```
[the remark this answers is not in the document]
Comment (blimlim) [reply source/ice_calendar.F90:591]: Good question. `use_leap_years` is used as a simulation-long setting to control whether a noleap or proleptic gregorian calendar is used.

`days_per_year` is reset every timestep with a call to [`set_calendar`](https://github.com/ACCESS-NRI/cice5/blob/9ebc312e030b76f3fd15159858ce8ca696f6a9e5/source/ice_calendar.F90#L539-L556). It describes the number of days in the current year. I.e. with the gregorian calendar, `days_per_year` will alternate between `365` and `366` depending on the year, whereas it will stay fixed at `days_per_year=365` for the noleap calendar.
